<?php
/**
 * autoActivateSuccessMessage.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/shippingfilters/LICENSE.txt
 *
 * @package       AuroraExtensions_ShippingFilters
 * @copyright     Copyright (C) 2020 Aurora Extensions <support@auroraextensions.com>
 * @license       MIT License
 */
?>
<?= $block->escapeHtml(
    __(
        'Auto-activated required localities. To disable auto-activation, click <a href="%1">here</a>.',
        $block->getData('config_url')
    ),
    ['a']
);
